"""add_story_content_type

Revision ID: 1916aeab9179
Revises: daf556d297f5
Create Date: 2026-07-15 03:34:18.549464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1916aeab9179'
down_revision = 'daf556d297f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_content', 'content_type',
               existing_type=mysql.ENUM('COURSE', 'ARTICLE', 'VIDEO', 'BOOK'),
               type_=sa.Enum('COURSE', 'ARTICLE', 'VIDEO', 'BOOK', 'STORY', name='content_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('learning_content', 'content_type',
               existing_type=sa.Enum('COURSE', 'ARTICLE', 'VIDEO', 'BOOK', 'STORY', name='content_type_enum'),
               type_=mysql.ENUM('COURSE', 'ARTICLE', 'VIDEO', 'BOOK'),
               existing_nullable=False)
    # ### end Alembic commands ###
