"""initial_mysql

Revision ID: c12ca0ba636c
Revises: 
Create Date: 2026-07-12 18:18:55.884009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12ca0ba636c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_messages_created_at'), 'coach_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_id'), 'coach_messages', ['id'], unique=False)
    op.create_index('ix_coach_messages_user_created', 'coach_messages', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_coach_messages_user_id'), 'coach_messages', ['user_id'], unique=False)
    op.create_index('ix_ai_insights_user_type', 'ai_insights', ['user_id', 'insight_type'], unique=False)
    op.create_index('ix_weekly_reports_user_date', 'weekly_reports', ['user_id', 'start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weekly_reports_user_date', table_name='weekly_reports')
    op.drop_index('ix_ai_insights_user_type', table_name='ai_insights')
    op.drop_index(op.f('ix_coach_messages_user_id'), table_name='coach_messages')
    op.drop_index('ix_coach_messages_user_created', table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_id'), table_name='coach_messages')
    op.drop_index(op.f('ix_coach_messages_created_at'), table_name='coach_messages')
    op.drop_table('coach_messages')
    # ### end Alembic commands ###
