"""add_goal_id_to_planner

Revision ID: daf556d297f5
Revises: ff82a1322833
Create Date: 2026-07-15 03:07:13.202428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf556d297f5'
down_revision = 'ff82a1322833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planner', sa.Column('goal_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'planner', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'planner', type_='foreignkey')
    op.drop_column('planner', 'goal_id')
    # ### end Alembic commands ###
