"""add_notification_type

Revision ID: ff82a1322833
Revises: c12ca0ba636c
Create Date: 2026-07-13 19:05:34.019157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff82a1322833'
down_revision = 'c12ca0ba636c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###
